<a href="https://colab.research.google.com/github/eche-ray/Business-Analysis/blob/main/Sql_practice(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import sqlite3

In [2]:
conn=sqlite3.connect('chinook.db')
cursor=conn.cursor()

In [3]:
cursor.execute("""SELECT name FROM sqlite_master WHERE type='table';""")
tables=cursor.fetchall()
print(tables)

[('albums',), ('sqlite_sequence',), ('artists',), ('customers',), ('employees',), ('genres',), ('invoices',), ('invoice_items',), ('media_types',), ('playlists',), ('playlist_track',), ('tracks',), ('sqlite_stat1',)]

SELECT + WHERE + ORDER BY

In [5]:
#Retrieve all customers from USA
df=pd.read_sql_query("""SELECT * FROM customers WHERE Country= 'USA';""",conn)
df.head()

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
1,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5
2,18,Michelle,Brooks,None,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
3,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3
4,20,Dan,Miller,None,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4

In [8]:
#Show employees ordered by hire date (newest first).
df=pd.read_sql_query("""SELECT EmployeeId, LastName, FirstName, HireDate FROM Employees ORDER BY HireDate DESC;""",conn)
df.head()

   EmployeeId  LastName FirstName             HireDate
0           8  Callahan     Laura  2004-03-04 00:00:00
1           7      King    Robert  2004-01-02 00:00:00
2           5   Johnson     Steve  2003-10-17 00:00:00
3           6  Mitchell   Michael  2003-10-17 00:00:00
4           4      Park  Margaret  2003-05-03 00:00:00

In [13]:
#Find invoices with totals greater than 15.
df=pd.read_sql_query("""SELECT * FROM Invoices WHERE Total>15;""",conn)
df.head()

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,88,57,2010-01-13 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,17.91
1,89,7,2010-01-18 00:00:00,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,18.86
2,96,45,2010-02-18 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,21.86
3,103,24,2010-03-21 00:00:00,162 E Superior Street,Chicago,IL,USA,60611,15.86
4,194,46,2011-04-28 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,21.86

In [14]:
#Display tracks longer than 5 minutes.
df=pd.read_sql_query("""SELECT * FROM invoice_items;""",conn)
df.head()

   InvoiceLineId  InvoiceId  TrackId  UnitPrice  Quantity
0              1          1        2       0.99         1
1              2          1        4       0.99         1
2              3          2        6       0.99         1
3              4          2        8       0.99         1
4              5          2       10       0.99         1

In [16]:
#Retrieve customers whose first name starts with “A”.
df=pd.read_sql_query("""SELECT FirstName FROM Customers WHERE FirstName LIKE 'A%';""",conn)
df.head()

   FirstName
0     Astrid
1  Alexandre
2      Aaron

AND OR IN & LIKE

In [18]:
#Find customers from USA or Canada.
df=pd.read_sql_query("""SELECT * FROM Customers WHERE Country= 'Canada' OR 'USA';""",conn)
df.head()

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
1,14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5
2,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
3,29,Robert,Brown,None,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,None,robbrown@shaw.ca,3
4,30,Edward,Francis,None,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,None,edfrancis@yachoo.ca,3

In [20]:
#Find invoices between $5 and $15.

df=pd.read_sql_query("""SELECT * FROM invoices WHERE Total BETWEEN 5 AND 15;""",conn)
df.head()

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,3,8,2009-01-03 00:00:00,Grétrystraat 63,Brussels,None,Belgium,1000,5.94
1,4,14,2009-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
2,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
3,10,46,2009-02-03 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,5.94
4,11,52,2009-02-06 00:00:00,202 Hoxton Street,London,None,United Kingdom,N1 5LH,8.91

In [22]:
#Retrieve employees with titles containing “Manager
df=pd.read_sql_query("""SELECT Title FROM Employees WHERE Title LIKE '%Manager';""",conn)
df.head()

             Title
0  General Manager
1    Sales Manager
2       IT Manager

In [23]:
#Find customers whose country is IN ('Brazil', 'Germany', 'France').
df=pd.read_sql_query("""SELECT * FROM Customers WHERE Country IN ('Brazil','Germany','France');""",conn)
df.head()

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
3,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
4,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3